openapi: 3.0.2
info:
  title: Api Gusto
  description: This is a REST API application for GustoSolution
  # termsOfService: 'http://swagger.io/terms/'
  # contact:
  #   email: apiteam@spotInc.fr
  # license:
  #   name: Apache 2.0
  #   url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
# externalDocs:
#   description: Find out more about Swagger
#   url: 'http://swagger.io'
servers:
  - url: 'http://localhost:3001/api'
  - url: 'https://api.gustosolutions'

tags: [  
    
    {
      "name": "Category",
      "description": ""
    },
    {
      "name": "Produit",
      "description": ""
    },
    {
      "name": "Utilisateur",
      "description": ""
    },
  
    {
      "name": "Menu",
      "description": ""
    },
    {
      "name": "Frigo",
      "description": ""
    }
  ]
paths:
  
  /category:
      get:
        tags: [Category]
        summary: Returns the list of all the categories.
        responses:
          '200':    # status code
            description: A JSON array of categories
            content:
              application/json:
                  example:
                    id_category: 1
                    label: fruits
                    image : https://www.google.com/imgres?imgurl=https%3A%2F%2Fmedia.istockphoto.com
                    description: some description
                    createdAt: 2021-11-26T13:38:27.000Z
                    updatedAt : 2021-11-26T13:38:27.000Z
                    fk_id_client: 8

      post:
        tags: [Category]
        summary: Permet d'ajouter une catégorie
        requestBody:
          required: true
          content:
            application/json:
              schema: 
                properties:
                  label:
                    type: string
                  image:
                    type: string
                  description:
                    type: string
                  fk_id_client:
                    type: integer
        responses:
          '200':    # status code
            description: A JSON array of categories
            content:
              application/json:
                  example:
                    id_category: 1
                    label: fruits
                    image : https://www.google.com/imgres?imgurl=https%3A%2F%2Fmedia.istockphoto.com
                    description: some description
                    createdAt: 2021-11-26T13:38:27.000Z
                    updatedAt : 2021-11-26T13:38:27.000Z
                    fk_id_client: 8
          '400':
            description: An error message
            content:
              application/json:
                  example:
                    message: "Missing required parameters"



  /category/{id}:
      get:
        tags: [Category]
        summary: Returns the specified category.
        parameters:
        - name: id
          in: path
          type: integer
          required: true
          description: Numeric ID of the category to get.
        responses:
          '200':    # status code
            description: A JSON array of categories
            content:
              application/json:
                  example:
                    id_category: 1
                    label: fruits
                    image : https://www.google.com/imgres?imgurl=https%3A%2F%2Fmedia.istockphoto.com
                    description: some description
                    createdAt: 2021-11-26T13:38:27.000Z
                    updatedAt : 2021-11-26T13:38:27.000Z
                    fk_id_client: 8
          '400':
            description: An error message
            content:
              application/json:
                  example:
                    message: "Category does not exists"

  /category/{id}/products:
      get:
        tags: [Category]
        summary: Returns all the product contained in thespecified category.
        parameters:
        - name: id
          in: path
          type: integer
          required: true
          description: Numeric ID of the category to get.
        responses:
          '200':    # status code
            description: A JSON array of products
            content:
              application/json:
                  example:
                    id_product: 1
                    label: pomme
                    image : https://www.google.com/imgres?imgurl=https%3A%2F%2Fmedia.istockphoto.com
                    price: 2
                    ubd: 11-01-2021
                    description: description
                    createdAt: 2021-11-26T13:38:27.000Z
                    updatedAt : 2021-11-26T13:38:27.000Z
                    fk_id_category: 8
          '400':
            description: An error message
            content:
              application/json:
                  example:
                    message: "Category does not exists or doest not have any product"


   
             